### ISSUE TITLE
Reordering of commits

### ISSUE THREAD

**Issue by John-Chan** [ForkIssues/TrackerWin#1938] opened 2023-06-15 09:04 UTC
When use github desktop / smartgit,I can drag a commit to reordering commits. Is fork support that?

**Comment by DanPristupov** [comment] 2023-06-15 09:10
Yes, if you start Interactive Rebase.

**Comment by DanPristupov** [comment] 2023-06-15 09:10
This is a duplicate of https://github.com/fork-dev/TrackerWin/issues/905

**Closed as completed** 2023-06-15 09:12 UTC
