### ISSUE TITLE
[Bug] Hiding a branch from the commit list breaks "Show lost commits (Reflog)"

### ISSUE THREAD

**Issue by andrewsm80** [ForkIssues/TrackerWin#1558] opened 2022-06-13 15:42 UTC
If I enable "View -> Show lost commits (Reflog)", I can see all additional commits in the reflog, as expected.
The problem is, if I then select a branch, and click "Hide 'some-branch-name' from the commit list",  all of the reflog commits disappear.

Also, the "Filtered by: ..." hint on top of the commit list isn't shown after clicking "Hide 'some-branch-name' from the commit list".

I'm running Fork 1.74.1.0 on Windows 10.

**Comment by DanPristupov** [comment] 2022-06-13 16:20
Duplicate of https://github.com/fork-dev/TrackerWin/issues/1514 and probably https://github.com/fork-dev/TrackerWin/issues/1307

**Closed as completed** 2022-06-13 19:25 UTC
