### ISSUE TITLE
Vertical scrollbar is practically invisible

### ISSUE THREAD

**Issue by jiripolcar** [ForkIssues/TrackerWin#1547] opened 2022-05-31 09:37 UTC
Attached screenshot is made in Windows 11. The position on the scrollbar is very hard to find in the color scheme.

The scroll bar should be in more contrast against the green/red change colours.

<img width="16" alt="image" src="https://user-images.githubusercontent.com/17983035/171143005-14a39ca4-70d8-4bf6-b3bb-e39358fc6662.png">

**Comment by DanPristupov** [comment] 2022-06-01 12:19
Duplicate of https://github.com/fork-dev/TrackerWin/issues/471

**Closed as completed** 2024-08-15 17:33 UTC
