### ISSUE TITLE
Fork hangs (and then dies) if discarding a new file with restricted permissions.

### ISSUE THREAD

**Issue by ronnieshipman** [ForkIssues/TrackerWin#2155] opened 2024-02-15 10:55 UTC
Hi.

If I attempt to 'Discard changes' on a new file with restricted permissions, the 'Discard changes' pop-up does not disappear and the spinning wheel stops spinning. Eventually Fork closes itself.

Fork version 1.94.1.0.

Here is a 'Discard changes' pop-up example:

![image](https://github.com/fork-dev/TrackerWin/assets/118984928/02717607-fc1b-4295-839a-73eae230560e)

Here is an example of a file with these extra restricted permissions:

![image](https://github.com/fork-dev/TrackerWin/assets/118984928/35cd76e2-c52a-4d52-8401-5c3309f64b2e)

Here is an example of a file with normal permissions:

![image](https://github.com/fork-dev/TrackerWin/assets/118984928/5c3b4e1d-0da7-4ca7-8c8e-145e88d1cd18)

To create a file with the restricted permissions and to see the problem.

- Go to C:\Program Files
- Right click | New | TXT File
- Allow the action to go ahead if asked by Windows.
- Right click on new file and select: Properties | Security tab
- The extra restricted permissions should be present.
- Move that file into a git repo that Fork knows about.
- Open Fork and select that repo tab (or equivalent).
- Select Local Changes
- Right click the file you have just moved in.
- Select: Discard changes...
- Click Discard.
- The pop-up should now hang and the spinning wheel should stop turning.
- In a few seconds (40 in my case) Fork should close itself.

Note that asking Task Manager etc to kill this process does not seem to make a difference to the time it takes for Fork to close itself.

I accept that this may be an obscure case, because why would you be creating files in the Program Files folder and moving them to a repo? This was a one off case and is not what I normally do. However, having seen the problem I felt I ought to report it.

What I would expect from Fork in this case is either
1. Something from Windows popping up to confirm I want this deleted (as Windows does when you do something in the Program Files folder). 
2. A pop-up saying that Fork cannot perform this function, with a good description why.

I hope this helps.

Kind regards,
Ronnie

**Comment by DanPristupov** [comment] 2024-02-15 11:00
Thank you for reporting this.

**Comment by DanPristupov** [comment] 2024-03-04 06:56
The problem is fixed in 1.95

**Closed as completed** 2024-04-03 10:54 UTC
