### ISSUE TITLE
[Feature request]Custom DateTime format support

### ISSUE THREAD

**Issue by aaasoft** [ForkIssues/TrackerWin#1393] opened 2021-11-25 05:43 UTC
Commit log time display in 'd MMM yyyy HH:mm' format，but I prefer to use 'yyyy-MM-dd HH:mm' format.Wish to custom DateTime format in 'Prefrences -> General'.

![1](https://user-images.githubusercontent.com/1552027/143386159-bc446c6e-09dd-4dc9-9c94-700c60f756e1.png)

**Comment by DanPristupov** [comment] 2021-11-25 09:19
Hi. This is a duplicate of https://github.com/fork-dev/TrackerWin/issues/1254

**Comment by aaasoft** [comment] 2021-11-25 11:23
Oh yes,this is a duplicate of #1254 ,sorry about this.

**Closed as completed** 2021-11-25 11:22 UTC
