### ISSUE TITLE
Submodules are not updated

### ISSUE THREAD

**Issue by jBitHub** [ForkIssues/TrackerWin#996] opened 2020-10-29 10:02 UTC
Fork has not updated submodules for over a year. I have reported this twice already. Somebody must have noticed something like this. The submodules can't be updated from directly either.

![grafik](https://user-images.githubusercontent.com/39560844/97553220-7b29d680-19d5-11eb-8437-3d8f7060ae41.png)
![grafik](https://user-images.githubusercontent.com/39560844/97553717-1622b080-19d6-11eb-9bd7-a059206aec71.png)

It is impossible to pull the new data.

**Comment by DanPristupov** [comment] 2020-10-29 10:25
> The submodules can't be updated from directly either.

What is the problem?

> It is impossible to pull the new data.

What error do you have in the output?

<img width="769" alt="Screen Shot 2020-10-29 at 11 24 57" src="https://user-images.githubusercontent.com/618115/97556189-67806f00-19d9-11eb-9c17-b9ab760de53c.png">

**Comment by jBitHub** [comment] 2020-10-29 11:04
Thanks for answer
Where can I see the window at the bottom right?
There is no error. The data is simply not updated.
The main module is updated. Only the submodules are not updated.
I used to install fork extra because it could update submodules. With some fork version it broke.

**Comment by DanPristupov** [comment] 2020-10-29 11:10
> Where can I see the window at the bottom right?

Click on the status control on the toolbar.

>  With some fork version it broke.

Is it possible that you need to enable 'Update submodules automatically' in Preferences?
<img width="563" alt="Screen Shot 2020-10-29 at 12 09 37" src="https://user-images.githubusercontent.com/618115/97560953-ae716300-19df-11eb-9ff4-22b413f753cf.png">

**Comment by jBitHub** [comment] 2020-10-29 11:20
Thanks for answer

![grafik](https://user-images.githubusercontent.com/39560844/97561618-bed60d80-19e0-11eb-8c57-ac7204fdef86.png)
I can't see any errors

![grafik](https://user-images.githubusercontent.com/39560844/97561714-dca37280-19e0-11eb-9abe-68bdb7b9bd94.png)
Is already switched on. As I said, it has worked before. Since about 1 year it does not work anymore.

**Comment by DanPristupov** [comment] 2020-10-29 11:32
So, Fork does perform `git submodule update --recursive` as you can see.

On the screenshots in the original post you have 38 uncommitted changes. Is it possible that the submodule reference is modified there and as a result it not affected by `git submodule update`? In other words, can you discard (or stash) those changes and try to pull again?

**Comment by DanPristupov** [comment] 2020-10-29 11:35
And BTW we missed the most important question. What is the expected behavior? Git will update a submodule only if the submodule HEAD != submodule reference committed in the parent repository.

**Comment by jBitHub** [comment] 2020-10-29 13:21
The 38 changes are only in the main module.
All changes are new files.
If the changes would cause problems, Git will return an error message. I've had this problem before. In this case there are no errors.

OK. I had Fork delete all changes. As expected there are no changes after pulling. All data in the submodules remain old. I have tried something like this before.

_And BTW we missed the most important question. What is the expected behavior? Git will update a submodule only if the submodule HEAD != submodule reference committed in the parent repository._

I do not understand the question. I want to have the latest data. 
The repository is not mine. I cloned the main module with fork in the beginning. In the beginning the submodules were updated. At some point all of a sudden it didn't work anymore. That's why I think it's a mistake by Fork.
What should I do now? What should I compare?

Thanks for your efforts

**Comment by DanPristupov** [comment] 2020-10-29 13:40
> OK. I had Fork delete all changes. As expected there are no changes after pulling. All data in the submodules remain old.

So far, looks like everything works properly.

> I want to have the latest data.

You must open the submodule and checkout the commit you want manually.
Git (and Fork) do not (and did not) checkout the latest changes automatically.

> What should I do now?

- Open parent repository
- Double click on the submodule to open it.
- Checkout the commit you want the submodule to be on
- Return to the parent repository
- Stage and commit the changes

**Comment by jBitHub** [comment] 2020-10-29 14:25
I have executed "Checkout Commit ...". Then a message appears.
![grafik](https://user-images.githubusercontent.com/39560844/97584908-d28d6e00-19f8-11eb-8ab6-9201cd515b70.png)

The data on the HD has been updated.
Now there are changes to the main module.
![grafik](https://user-images.githubusercontent.com/39560844/97585371-5d6e6880-19f9-11eb-86a0-8211c65cf07f.png)
After that press "Stage".
![grafik](https://user-images.githubusercontent.com/39560844/97585532-87c02600-19f9-11eb-80e3-aa2204812cfa.png)

_Stage and commit the changes_
"Commit"? Where should I make a commit? The repository is not mine. I am not allowed to upload changes. Besides, nothing has really changed.

_Git (and Fork) do not (and did not) checkout the latest changes automatically._
The statement cannot be true. I created the repository on 13 November 2018. Until 26 August 2019 everything was downloaded automatically. You can see that on the picture. This also corresponds with the display in Fork. After that there was some fork update and it did not work anymore.
![grafik](https://user-images.githubusercontent.com/39560844/97586635-c60a1500-19fa-11eb-8447-6fa66972fdbb.png)

**Comment by DanPristupov** [comment] 2020-10-29 14:57
> The repository is not mine. I am not allowed to upload changes. Besides, nothing has really changed.

I guess the repository owner decided that you must not use the latest version of the submodule yet. May be the feature is not ready, or something.

> I created the repository on 13 November 2018. Until 26 August 2019 everything was downloaded automatically.

OK.

> You can see that on the picture.

Yes.

> After that there was some fork update and it did not work anymore.

I don't agree. The repository points to the correct commit in the submodule. Everything is in sync.

May be I don't understand something, but you need to explain what exactly does not work anymore. What do you expect Fork to do? Do you think it must checkout the latest commit in the submodule? No, it definitely must NOT.

**Comment by DanPristupov** [comment] 2020-10-29 15:08
I just checked that repo.

The submodule points to `70e4a2c - Workarounds for FPC AArch64 Android Target` only because it was committed 25 Aug 2019 at 03:23 `5b7c7f8 - Updated externals`

<img width="818" alt="Screen Shot 2020-10-29 at 16 04 17" src="https://user-images.githubusercontent.com/618115/97591945-6b73b780-1a00-11eb-9f1d-66f28add6841.png">

This is the last commit which switches the submodule HEAD/point.

May be you can ask Benjamin Rosseaux about the reason he 'did not update the submodules in his repo for over a year' right here by referencing him :)

**Comment by jBitHub** [comment] 2020-10-30 12:32
Thank you very much for your answer and help.
I will get in touch with Benjamin Rosseaux.
I would not have thought of it alone.

**Comment by DanPristupov** [comment] 2020-10-30 13:27
I'm reading the answer in the other topic

**Comment by DanPristupov** [comment] 2020-10-30 13:51
Just want to let you know that Benjamin @BeRo1985 just updated the submodule references.

**Comment by DanPristupov** [comment] 2020-10-30 14:01
It was quite a detective story 😀
I think we can close this issue now

**Comment by jBitHub** [comment] 2020-10-30 15:21
Thank you again for helping me so much. I would never have thought that things would turn out like this. Yes - to a detective story.
😀
Oh - now all submodules are up to date.

**Closed as completed** 2020-11-02 06:32 UTC
