### ISSUE TITLE
VirusTotal is detecting a trojan in the installer (Windows)

### ISSUE THREAD

**Issue by laurin1** [ForkIssues/TrackerWin#6] opened 2018-07-18 12:38 UTC
https://www.virustotal.com/en/file/6ffda3f17d47770869c6bc94de3e27ce906873808538c0e437283a2d6ed9ea7f/analysis/

![image](https://user-images.githubusercontent.com/75857/42881708-99e92724-8a5d-11e8-9f2c-2c725d4e97dd.png)

**Comment by SebRut** [comment] 2018-07-18 12:46
My guess would be that the use of [Squirrel](https://github.com/Squirrel/Squirrel.Windows) as an installer triggers these. Maybe some malicious program uses Squirrel as well.

**Comment by DanPristupov** [comment] 2018-07-18 13:15
The problem is clearly in Squirrel, but I'm not sure how to solve that yet. Both Fork binaries and the installation package are signed, which in theory should help to protect from such cases.

Just submitted Fork as false-positive to McAfee. We'll see how it work out.

I could't find a way to make a similar request to Kaspersky.

**Comment by SebRut** [comment] 2018-07-18 13:29
Kaspersky: https://virusdesk.kaspersky.com

**Comment by DanPristupov** [comment] 2018-07-24 12:20
Still no response. 
Other news is that Zillya appeared in that list as well. I sent them the false-positive report too.

**Comment by DanPristupov** [comment] 2018-07-26 12:24
OK, Rising, got fixed but 2 new appeared.
May be I should stop using Squirrel, not sure.

**Comment by SebRut** [comment] 2018-07-26 12:26
Maybewe should contact the squirrel devs and bring this to their attention.

**Comment by SebRut** [comment] 2018-07-26 12:28
We could also try to mass submit as described on this site: https://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm#Easily_Submit_Malware_To_All_Vendors

**Comment by DanPristupov** [comment] 2018-07-26 12:49
> Maybewe should contact the squirrel devs and bring this to their attention:

They are aware:
https://github.com/Squirrel/Squirrel.Windows/issues?utf8=✓&q=is%3Aissue+virus

**Comment by SebRut** [comment] 2018-07-26 12:53
Seems like they suggest to sign your launcher to get rid of false positives.  (https://github.com/Squirrel/Squirrel.Windows/issues/1249) IIRC Fork does this but still gets flagged.

**Comment by DanPristupov** [comment] 2018-07-26 13:04
Of course Fork is signed. Nowadays you won't even be able to run an executable file if it's not signed.

<img width="520" alt="2018-07-26 at 15 03" src="https://user-images.githubusercontent.com/618115/43263993-213459aa-90e5-11e8-8ee8-f1fbf339be78.png">

**Comment by oneingfw** [comment] 2018-08-04 14:43
on my personal pc,kaspersky report the download link is malicious.
on my working laptop,symantec blocked the installer.

**Comment by DanPristupov** [comment] 2018-08-23 07:09
I finally got a first response :)

> Hello, 
> 
> Sorry, it was a false detection. It will be fixed. 
> Thank you for your help. 
> 
> Best regards, 
> Rassokhin Kirill, Malware Analyst, Kaspersky Lab 

P.S. To be fair, the answer was sent 14 Aug, but got caught by spam filter (see the irony?)

**Comment by DanPristupov** [comment] 2019-02-12 11:22
It looks like we can close this now.

<img width="1013" alt="screenshot 2019-02-12 at 12 24 15" src="https://user-images.githubusercontent.com/618115/52632210-2670c000-2ec1-11e9-95d5-2eeaecfee141.png">

**Closed** 2019-02-12 11:25 UTC
