### ISSUE TITLE
Auto pin the checked out branch

### ISSUE THREAD

**Issue by vbasky** [ForkIssues/TrackerWin#1323] opened 2021-10-01 01:54 UTC
It would be handy to have a setting like a check box to enable when checking out a branch / branch only to pin it on the sidebar. Currently I manually have to pin only a certain branch that I am working on. It would be a nice feature to have. Please consider

**Comment by DanPristupov** [comment] 2021-10-01 06:50
This seems like a duplicate of https://github.com/fork-dev/TrackerWin/issues/709

**Closed as completed** 2022-08-12 01:44 UTC
