### ISSUE TITLE
Submodule Workflow Feature Requests

### ISSUE THREAD

**Issue by StephenHodgson** [ForkIssues/TrackerWin#743] opened 2020-04-19 07:47 UTC
Love the product. 

I have a small feature to ask when it comes to submodule workflow. 

Currently when you open a submodule it's usually checked out to a detached head. Is there any way to automatically checkout the branch that the parent repo is targeting, so when I open a submodule I can stage those changes and commit faster?

Cheers, and thanks for an amazing tool.

**Comment by felixhirt** [comment] 2020-09-17 14:03
Possible duplicate of #569

**Comment by StephenHodgson** [comment] 2021-06-04 05:15
Seems to do the trick
```
git submodule foreach -q --recursive 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch)'
```

**Comment by StephenHodgson** [comment] 2021-06-04 08:20
I came up with a solution:
```
git submodule foreach -q --recursive 'echo $name && git switch -C $(git name-rev --exclude=refs/tags/\* --name-only $(git rev-parse @{-1}))'
```

**Closed as completed** 2022-12-18 16:55 UTC
