### ISSUE TITLE
Continue request of login

### ISSUE THREAD

**Issue by manuelelucchi** [ForkIssues/TrackerWin#410] opened 2019-08-27 21:45 UTC
Hi, Fork is very cool but on Windows it continues to ask me credentials for Github (using the Git Credential Manager), with 2 login windows at time and even if i put my credentials in all of them they will continue to spawn. If I don't use the pc for some minutes with fork opened I find dozens of windows opened. Is it a known issue? In the Mac version i saw you can explicitly connect your account like in this image
![image](https://user-images.githubusercontent.com/17146198/63810284-ad98f900-c924-11e9-885b-22468567415b.png)
Will it be available also for windows?

Regards, 
Manuele

**Comment by DanPristupov** [comment] 2019-08-28 05:41
> Fork is very cool but on Windows it continues to ask me credentials for Github (using the Git Credential Manager), with 2 login windows at time and even if i put my credentials in all of them they will continue to spawn.

Unfortunately this is a bug (or feature!) in https://github.com/microsoft/Git-Credential-Manager-for-Windows which is part of the Git for Windows.
If I remember correctly this is a feature, because GCM erases your credentials when it can't connect to the server (which usually happen when you have a bad connection in some cafe).

I will try to debug their code and give more info about the problem.

As for now, please consider automatic fetch or just continue closing the windows (this is what I do).

**Comment by manuelelucchi** [comment] 2019-08-28 08:13
I disabled the automatic fetch and now it doesn't seem to spawn windows anymore, thanks! Looking forward for a better workaround

**Comment by Geobert** [comment] 2019-11-19 09:40
same here, came back this morning with the PC full of login windows and after closing them, many git process trees to kill ^^'

**Comment by DanPristupov** [comment] 2019-11-19 10:11
Same here. It just happens randomly after computer went sleep.
I probably should try to find out why this happens (and hopefully help the developers to fix it).

**Comment by DanPristupov** [comment] 2019-11-22 15:20
The developers of GCM don't respond, however I think I managed to fix the login-rush problem on my side.

Please update to 1.42 and give me some feedback after some time of use.

**Comment by DanPristupov** [comment] 2019-11-24 19:47
I just want to add, that the problem is not 100% fixed, however should happen less often. Not sure *how* often though, we will see.

**Comment by Annika-Houkes** [comment] 2019-11-28 08:40
Cheers, I updated to 1.42 yesterday (1.42.4.0) and it happened this morning, however like you said it's not a 100% fix! I'll disable automatic fetch and close the other issue, thanks for the link.

**Comment by DanPristupov** [comment] 2019-11-28 08:52
I just want to mention that GCM developers still don't respond.

Regarding the problem, for me everything worked fine whole week but got broken when I used public wifi. Looks like I must go there again to reproduce it :).

**Comment by Geobert** [comment] 2019-11-28 09:02
I had one or two requests, but no more swarm of request windows

**Comment by DanPristupov** [comment] 2019-11-28 09:06
Currently (1.42), Fork checks the internet connection before starting the automatic fetch. In theory this should fix the problem, however there are cases when it doesn't (may be when computer goes to sleep during fetch?).

**Comment by Geobert** [comment] 2019-11-28 09:36
Oh, strange then, as the laptop was not sleeping. Do you check the connection to the repository or only if there is a network? As the laptop is in a corporate network, the laptop may had network but without internet connectivity?

**Comment by DanPristupov** [comment] 2019-11-28 10:11
It's actually a bit tricky there. Fork tries to establish an https connection with the **corresponding** website. So, if you use GitHub, Fork will check https://github.com. For BitBucket it will use https://bitbucket.org.

**Comment by Geobert** [comment] 2019-11-28 10:13
Ok so my hypothesis of a corporate network without an Internet connection can't work. I'm wondering what happened then, a hiccup from github?

**Comment by DanPristupov** [comment] 2019-11-28 10:16
@Geobert if you are interested, I can tell how to enable verbose logging on your computer to investigate that problem (please send me an email to winsupport@forkapp.io).

Other volunteers are also welcome :).

**Comment by DanPristupov** [comment] 2019-12-09 09:57
Hi!

I think I fixed the problem ☀️.

The new version is available here https://fork.dev/update/win/ForkInstaller.exe (the installer will reset preferences, so please backup `%localappdata%\Fork\settings.json` if you have custom commands or issue tracker rules).

I would appreciate if you give it a try and leave some feedback.

Right we are testing it ourselves. If everything is OK, I will release the hotfix update during the week.

**Comment by DanPristupov** [comment] 2019-12-09 09:58
Hi!

I think I fixed the problem ☀️.

The new version (1.41.5.0) is available here https://fork.dev/update/win/ForkInstaller.exe (the installer will reset preferences, so please backup `%localappdata%\Fork\settings.json` if you have custom commands or issue tracker rules).

I would appreciate if you give it a try and leave some feedback.

Right we are testing it ourselves. If everything is OK, I will release the hotfix update during the week.

**Comment by Geobert** [comment] 2019-12-13 10:38
running it since Tuesday, nothing to report for the moment, I'll let the test run over the week end.

**Comment by DanPristupov** [comment] 2019-12-13 11:04
Same on my side 👍. I will release the hotfix for all users today.

**Comment by DanPristupov** [comment] 2019-12-13 16:20
Just released the 1.0.42.**6** hotfix (it will also update git to 2.24.1)

**Closed as completed** 2020-02-27 23:09 UTC
