### ISSUE TITLE
External diff on multiple selected files in changelist

### ISSUE THREAD

**Issue by anubloom** [ForkIssues/TrackerWin#554] opened 2019-11-14 13:25 UTC
Many diff utils such as BeyondCompare, WinMerge can handle multiple diffs within one application window. So please enable External Diff on more than one selected file. Awesome product, but just for this workflow, I have to currently use other git clients.

**Comment by kimsey0** [comment] 2020-01-15 09:01
Is this a duplicate of #113?

**Comment by fklappan** [comment] 2021-04-30 18:52
> 
> 
> Is this a duplicate of #113?

Yes.

**Closed as not planned** 2023-10-03 12:55 UTC
