### ISSUE TITLE
Fork crash when try to close File History window

### ISSUE THREAD

**Issue by zrpfpr** [ForkIssues/TrackerWin#229] opened 2019-04-12 06:55 UTC
Select one file and open File History. When try to close using Close button Fork freezes 

![image](https://user-images.githubusercontent.com/6117119/56017822-b2a43580-5d00-11e9-8872-b84364adc01a.png)

**Comment by Otiel** [comment] 2019-04-25 08:17
Cannot reproduce. Any specific character in the file path?

**Comment by DanPristupov** [comment] 2019-04-25 08:43
@Otiel Pressing the Close button (in the right bottom corner) is enough. The escape key also does the job :).

**Comment by Otiel** [comment] 2019-04-25 08:59
My bad, I tried to click the "X" button instead of "Close".

**Comment by DanPristupov** [comment] 2019-04-26 10:11
Fixed in Fork 1.32. Please check for updates.

**Closed as completed** 2019-05-13 09:11 UTC
