### ISSUE TITLE
Do not switch to "All Commits" upon commit

### ISSUE THREAD

**Issue by valhristov** [ForkIssues/TrackerWin#765] opened 2020-04-28 15:21 UTC
I could not find a similar issue, feel free to close this as duplicate if one exists.

Since recently Fork started navigating to the "All Commits" page upon committing changes. This is quite annoying in case I am trying to split the changes I have made in multiple commits.

~~I would like to have this behavior configurable, so that I can turn it off. (I could not find a suitable setting in settings.json, if there is one, please, let me know :-))~~

~~Another option, perhaps better, would be to stay on the "Changes" screen if there are uncommitted files...~~

See [steps to reproduce](https://github.com/ForkIssues/TrackerWin/issues/765#issuecomment-620856528)

**Comment by DanPristupov** [comment] 2020-04-28 15:27
> Since recently Fork started navigating to the "All Commits" page upon committing changes. 

If this is true, it's definitely not a feature, but a bug. Can you write steps to reproduce the issue, because I've never seen it.

**Comment by valhristov** [comment] 2020-04-28 20:53
Looks like if there is a selection in the treeview on the left, after commit, Fork navigates to "All Commits".

**Comment by valhristov** [comment] 2020-04-28 21:09
One way to do it:

1 - Select "All Commits"
2 - Select the current branch on the left (it becomes blue)
3 - Select "Changes" (the selected branch is gray)
4 - Stage files
5 - Enter commit message
6 - Press "Commit" (application navigates to "All Commits")

![image](https://user-images.githubusercontent.com/23195959/80538064-5bbddc80-89a5-11ea-9659-44a823082e37.png)

**Comment by DanPristupov** [comment] 2020-06-01 07:59
Fixed in 1.50.

Thank you for the bug report 👍

**Comment by Lucas-Nt** [comment] 2020-09-11 11:00
If I understood correctly this was a bug but could this be somehow added as an option in the near future? 
And let's say have a condition to check if all files in **Changes** have been committed, then go to **All Commits** view.

Because as it is now, when all changes are commited, we are left in an empty view and need to click manually to navigate to **All Commits**.

Just a suggestion

**Closed as completed** 2023-06-08 06:18 UTC
