### ISSUE TITLE
issue with "Save commit as patch"

### ISSUE THREAD

**Issue by TheFerrango** [ForkIssues/TrackerWin#436] opened 2019-09-13 07:47 UTC
When saving a commit as a patch, if the destination folder has a space in its name, the command returns an error and does not save the patch, prompting instead the following output:

```
fatal: ambiguous argument 'cartella': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

It's probably just the destination path needing to be in quotes. It works fine if the destination path has no spaces in it

**Comment by DanPristupov** [comment] 2019-10-04 15:01
Fixed in 1.40. Please check for updates

**Closed as completed** 2019-10-15 14:51 UTC

**Comment by d1vanloon** [comment] 2019-11-20 22:42
I still see this issue on version 1.41.1.0.

Is there any additional information I can provide?

**Comment by DanPristupov** [comment] 2019-11-21 06:09
@d1vanloon reporting the problem is enough. Thanks.

**Comment by DanPristupov** [comment] 2019-11-22 15:24
Fixed again in 1.42 :)
