### ISSUE TITLE
[Feature Request] Add an option in preferences to automatically track the newly pushed branch without being asked via a dialog.

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#929] opened 2020-08-28 23:15 UTC
Title says it all.

**Comment by DanPristupov** [comment] 2020-09-19 14:44
This seems to be a duplicate of https://github.com/ForkIssues/TrackerWin/issues/763

**Comment by XtroTheArctic** [comment] 2020-09-19 15:01
Yes, the same thing.
I hope this can be added soon.

**Closed as completed** 2020-09-19 15:11 UTC
