### ISSUE TITLE
fatal: NullReferenceException encountered

### ISSUE THREAD

**Issue by warnat** [ForkIssues/TrackerWin#51] opened 2018-11-23 15:35 UTC
After the last update to version 1.23.5.0, **push and pull will always fail** with

fatal: NullReferenceException encountered.
   Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
(Object reference not set to an instance of an object)

Thanks for looking into this.

**Comment by jerone** [comment] 2018-11-23 17:10
Duplicate of https://github.com/ForkIssues/TrackerWin/issues/49.

**Comment by warnat** [comment] 2018-11-23 22:39
but GCM 1.18.3 did not help

**Comment by beppler** [comment] 2018-11-24 20:00
You should update the git that comes with git-fork, not the main git install on your machine.
It worked when I unzipped the GCM ZIP on folder `gitInstance\2.19.1\mingw64\libexec\git-core` inside the git-fork install folder.

**Comment by warnat** [comment] 2018-11-25 17:27
Thank you.  
I replaced the content of the gitinstance/2.19.1 with the content of https://github.com/git-for-windows/git/releases/download/v2.19.2.windows.1/PortableGit-2.19.2-64-bit.7z.exe  
Now everything seems to work again.

Thanks for pointing me to the right direction.

**Comment by DanPristupov** [comment] 2018-11-25 18:09
Let's keep it open until I release the new build.

**Comment by DanPristupov** [comment] 2018-11-26 10:55
Just released Fork 1.24 with git 1.19.2 and some other features.

Please check for updates and let me know if the problem is fixed.

**Comment by warnat** [comment] 2018-11-26 14:29
It's working fine on my machine. Thanks for the Update.  
And also thanks for the great tool!

**Comment by DanPristupov** [comment] 2018-11-26 14:44
Awesome! Thank you for your involvement!
Closing the issue now.

**Closed as completed by DanPristupov** 2018-11-26 14:44 UTC
