### ISSUE TITLE
"Show hidden symbols" displays '\n' for CRLF lines

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#189] opened 2019-03-06 07:55 UTC
Why show single char when there is two?

**Comment by DanPristupov** [comment] 2019-03-06 08:06
Most probably there aren't. Check your `core.autocrlf` settings if you want to use a different separator.

part of git diff output:
```
warning: CRLF will be replaced by LF in filename.
The file will have its original line endings in your working directory
```

**Comment by sm-g** [comment] 2019-03-06 18:56
I have `autocrlf = true`. 
I'm looking at C# files and I'm sure they have CRLF endings.

**Comment by jerone** [comment] 2019-03-07 08:52
Actually, I can confirm this...

This is Fork (commit changes):
![image](https://user-images.githubusercontent.com/55841/53943799-33e32980-40be-11e9-9707-7e4bdf3d9594.png)

And this is Notepad++ for the same file (without the deletions):
![image](https://user-images.githubusercontent.com/55841/53943890-69881280-40be-11e9-8182-23939d904187.png)

I also have:
```
[core]
	autocrlf = true
```

**Comment by DanPristupov** [comment] 2019-03-07 08:59
Could you run the following in command line:
`git diff -- RouteConfig.cs > gitOutput.txt`

What line endings will be in `gitOutput.txt`?

**Comment by jerone** [comment] 2019-03-07 09:14
I already committed that file. That screenshot was from commit changes. Will try a new file...

Fork:
![image](https://user-images.githubusercontent.com/55841/53945183-5460b300-40c1-11e9-9038-1fbbc6e10f73.png)

Notepad++:
![image](https://user-images.githubusercontent.com/55841/53945250-7eb27080-40c1-11e9-85dd-fd164be9ee83.png)

After running that command in `gitOutput.txt` with Notepad++ (same in Fork):
![image](https://user-images.githubusercontent.com/55841/53945333-ac97b500-40c1-11e9-9f7b-773d8f8ff707.png)

**Comment by DanPristupov** [comment] 2019-03-07 09:19
I think that is correct. I mean, this is how git shows the diff output.

Most probably in terminal you've got the following warning:
```
warning: CRLF will be replaced by LF in filename.
The file will have its original line endings in your working directory
```

**Comment by DanPristupov** [comment] 2019-03-07 09:20
I can make Fork to not show the line ending symbol to avoid the confusion (since the exact EOL symbol doesn't make much sense anyway).

**Comment by DanPristupov** [comment] 2019-03-22 17:03
OK, in 1.30 we don't have '\n' symbol anymore :)

**Comment by jerone** [comment] 2019-03-22 17:25
So, if someone makes a change in line-ending, Fork will show the line as changed, but I can't see _what_ changed...

**Comment by DanPristupov** [comment] 2019-03-22 17:37
I think git will change the EOL symbol on commit. (UPDATE: even on stage!)

Just to clarify: usually git uses the same EOL symbol internally. And it replaces the EOL symbols on checkout and on commit.

Explanation from Stackoverflow (https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf):

```
core.autocrlf=true:      core.autocrlf=input:     core.autocrlf=false:

        repo                     repo                     repo
      ^      V                 ^      V                 ^      V
     /        \               /        \               /        \
crlf->lf    lf->crl      crlf->lf       \             /          \      
   /            \           /            \           /            \
```

As you can see, you can't commit wrong EOL symbol, until you turn off `autocrlf` (which is also not a problem if you use core.autocrlf=true)

**Comment by jerone** [comment] 2019-03-23 09:42
Ok, that makes sense. Thank you.

But then Fork should not show the file with changed EOL symbols as changed.

**Closed as completed** 2019-04-07 12:05 UTC

**Comment by sm-g** [comment] 2019-10-04 18:44
@DanPristupov at now there is no "\n" (or "\r\n") in this mode at all. By design?

**Comment by DanPristupov** [comment] 2019-10-04 20:46
@sm-g depends on your `core.autocrlf` config settings.

**Comment by nearorbit** [comment] 2021-08-17 12:36
Changes to line-endings (I think, because everything else looks the same) now look like this, without any option to see what changed into what :(. Ignore whitespaces doesn't prevent this from happening.

![image](https://user-images.githubusercontent.com/61239530/129726402-1b2ad67e-d2c1-4690-8cb0-8051c57b465f.png)

**Comment by DanPristupov** [comment] 2021-08-17 14:08
@HnngKoos you can understand more about the problem by checking hex in some editor
