### ISSUE TITLE
New error in 1.67 - external diff gives error on branch 

### ISSUE THREAD

**Issue by octavobr** [ForkIssues/TrackerWin#1342] opened 2021-10-16 06:03 UTC
Hello,

I am getting this error when trying to compare with external diff a file from a branch (**and the file is not existing on my current branch and it was just added on that branch**):

$ git -c core.longpaths=true --work-tree=***\Local\Temp\Fork\2e64310~ restore --source=2e64310f9a1785ebe22b97499142251a2aca46cd~ --***file.c

error: pathspec '***file.c' did not match any file(s) known to git

![Capture](https://user-images.githubusercontent.com/86507649/137575831-22b49b4e-c897-4c97-8aa3-c06ed36af044.PNG)

Thank you.

**Comment by DanPristupov** [comment] 2021-10-16 08:12
Hi,

> the file is not existing on my current branch and it was just added on that branch

Looks like we need to disable the internal diff option for new and deleted files. There's nothing to compare anyway.

**Comment by octavobr** [comment] 2021-10-16 08:18
Hello,

Previously it allowed to view new files from other branches in the external editor without checking them out, since "Open" does not work. It was a nice feature...

Thank you.

**Comment by octavobr** [comment] 2021-10-16 09:24
Also this feature brought fluidity to the user experience. Whenever I select or compare commits I can just click on a file and hit CTRL+D and I know the external diff(editor) will open and compare/review the file quickly, regardless of the file status (new, deleted, renamed) or on which branch it was etc.

Please don't remove this feature :)

Thank you.

**Comment by DanPristupov** [comment] 2021-10-16 14:57
> Also this feature brought fluidity to the user experience...

Thank you for the explanation. I understand the problem better now 👍. I didn't realize it is a **feature**, before I read your post :).

> Previously it allowed to view new files from other branches in the external editor without checking them out, since "Open" does not work

That was a bug actually :). In Fork for Mac the 'external diff' menu item for new and deleted files has always been disabled.

The problem is that the majority of external editors requires 2 versions of file in order to show diff for them. But for an added or removed file, it's only one version. Previously Fork created a 'dummy' file for the missing version.

Why have that become a problem now? Well, we are moving toward support for external diff for multiple files and folders and ensuring that each file in a massive diff has a pair could be a problem.

Again, I didn't know that was a feature. I will try to bring it back.

**Comment by DanPristupov** [comment] 2021-10-17 11:03
As I said:
> The problem is that the majority of external editors requires 2 versions of file in order to show diff for them. But for an added or removed file, it's only one version. Previously Fork created a 'dummy' file for the missing version.

It looks like we can't make external diff work for new/deleted files everywhere anyway. For example in the 'Local Changes' view for deleted files when you compare 'committed version' and the 'actual file' because we can't create dummy files in the working directory. External diff for new and deleted files must be disabled there.

**Comment by octavobr** [comment] 2021-10-18 05:24
Hello,

OK, understood :) 
Btw in the new 1.67 there is a noticeable delay (2-3) seconds when pressing CTRL+D to open the external diff, previously it was instant. Also it gives an error when using external diff on files which have spaces in the file name e.g "test file.txt".

Thank you.

**Comment by DanPristupov** [comment] 2021-10-18 06:14
> it gives an error when using external diff on files which have spaces in the file name e.g "test file.txt".

Thank you. I'm fixing that right now.

> Btw in the new 1.67 there is a noticeable delay (2-3) seconds when pressing CTRL+D to open the external diff, previously it was instant.

Ouch. Yes, you are right. :(. The new `git restore` command (https://git-scm.com/docs/git-restore) seems to be extremely slow on Windows. On MacOS same operation takes ~10ms.

**Comment by DanPristupov** [comment] 2021-10-18 06:24
It looks like GitLFS is what makes that operation slow. Do you use LFS? Is there the `lfs` folder in the `.git` directory in your repo?

**Comment by octavobr** [comment] 2021-10-18 06:27
Hello,

Yes, we use git LFS.

**Comment by DanPristupov** [comment] 2021-10-27 09:19
I rewrote the external diff functionality and made it fall back to the native `git difftool` command. It must work properly with LFS and also be faster that the latest release.

I made a preview build with those changes. Can you try if it works for you?

https://cdn.fork.dev/prerelease/Fork-1.67.11.zip

To use it, just extract the .zip somewhere and run `fork.exe`.

**Comment by octavobr** [comment] 2021-10-27 10:38
Hello,

With the old 1.67.1.0 it is better (instant) because I de-initialized LFS and the external diff opens instantly.
I tested the new version 1.67.1.1 unfortunately the delay is still noticeable (both with LFS and without LFS !).

Thank you

**Comment by DanPristupov** [comment] 2021-10-27 12:06
Can you say how bad is the delay now? It it any better than you initially had with 1.67.1?

Currently there are 3 solutions. Each of them have problems and I need to choose the better one.
- `< 1.66` - Fork handled everything by itself. It was fast, but didn't work with LFS files and could not allow us to introduce directory diff in the future. May be I can make it work with LFS, but directory diff is impossible for sure.
- `1.67.1` - Fork uses `git checkout` command. I works well with LFS and directories. However turned out that `git checkout` **always** calls post-checkout hook which might be slow (for LFS) or even fail (if that hook is used to repository validation).
- `1.67.11` - Fork uses `git difftool` command, which is the same as if you would run diff tool from the command line. I miss the control over things which happen under the hood, but I expected that approach to be faster than `1.67.1` because it doesn't call hooks. Directory diff must also be possible.

**Comment by octavobr** [comment] 2021-10-27 12:15
Hello,

The delay on 1.67.1.1 is comparable with the one on 1.67.1 (maybe just a little less delay).
I personally like the < 1.66, but I think also that the one in 1.67.1 is a good compromise (because I can disable LFS and it speeds up).

Thank you.

**Comment by DanPristupov** [comment] 2021-10-27 13:11
I measured the duration between click and the time of the diff tool UI appearance using (http://isitsnappy.com). I made 3 measures for each case and then calculated the average time. All tests were made on non-LFS files.

### Repo without LFS

`1.66` (manual) - **best**
624 ms

`1.67.1` (git checkout)
712 ms (+88 ms)

`1.67.11` (git diff tool)
755 ms (+131 ms)


### Repo with enabled LFS

`1.66` (manual) - **best**
725 ms

`1.67.1` (git checkout)
2,535 ms (+1,810 ms)

`1.67.11` (git difftool)
858 ms (+135 ms)


So, 1.67.11 seems to add 135 ms to the original operation duration in 1.66. This is fine, I think.

Can you check if 1.66 was really much faster for you? I uploaded it as zip here: https://cdn.fork.dev/prerelease/Fork-1.66.zip

**Comment by octavobr** [comment] 2021-10-27 13:20
Hello,

1.66 was instant (always), same speed as 1.67.1 without LFS enabled.
1.67.11 is slow (with or without LFS). (I use Windows 10)

Thank you.

**Comment by DanPristupov** [comment] 2021-10-27 16:24
Did you check the 1.66 build above? As I said, I'd measured the time and the speed was almost the same as 1.67.11.

**Comment by octavobr** [comment] 2021-10-27 17:07
Hello,

I've retested again on my home computer with Windows 7 all 3 variants and I guess it's my fault for not explaining in detail what happens. When pressing ctrl+d on a file:

1.66
without git LFS / with git LFS :
the circle appears near the cursor immediately (cursor changes shape), stays like this for 1(2) second then editor opens

1.67.1.0
without git LFS:
the circle appears near the cursor immediately, stays like this for 1(2) second(s) then editor opens
with git LFS :
after a delay of 1(2) second(s) the circle appears near the cursor, stays for 1(2) second then editor opens

1.67.11
with git LFS/with git LFS:
after 2(3) seconds delay the circle appears near the cursor and the external editor opens immediately

Basically I did not describe correctly what I meant by 'instant". As you can see on 1.66 as soon as I press ctrl+d the cursor changes from normal arrow to an arrow+circle (indicating progress) then after a delay editor opens. Same as in 1.67.1.0 without LFS.

But in 1.67.1.0 with LFS and in the new 1.67.11 when pressing ctrl+d nothing happens for about 2(3) seconds (while you can do other things), then the cursor changes to arrow+circle and (quick) after the editor opens.

Though the timing might be similar of opening the editor in these versions (a little more or less)... When you press ctrl+d and nothing happens for 2(3) seconds it gives you the feeling that there is a delay. Meanwhile on the 1.66(1.67.1.0 withotu LFS) as soon as you press ctrl+d the cursor changes shape and the feeling is that there is no delay.

Thank you :)

**Comment by octavobr** [comment] 2021-10-28 05:52
Hello,

With my work computer with Windows 10 (which is more performant) it's a little different, but the delay is still there.

1.66
without git LFS / with git LFS :
the circle appears near the cursor immediately (cursor changes shape), then editor opens shortly after

1.67.1.0
without git LFS:
the circle appears near the cursor immediately, then editor opens shortly after
with git LFS :
after a delay of 1(2) second(s) the circle appears near the cursor, then editor opens shortly after

1.67.11
with git LFS/with git LFS:
after 2(3) seconds delay the circle appears near the cursor and the external editor opens immediately

The delay is more noticeable with a performant computer. Nothing happens for a few seconds after pressing ctrl+d then the editor opens immediately (1.67.1.0 with LFS and 1.67.11). 

Thank you :)

**Comment by DanPristupov** [comment] 2021-11-10 17:07
Hi. I'm still trying to find a better solution. I made a new build which basically returns to what we had had before, but handles LFS properly. Can you check if external diff works properly on your side?

The build is available here: https://cdn.fork.dev/prerelease/Fork-1.68.10.zip Same as before, just extract the archive somewhere and run fork.exe.

**Comment by octavobr** [comment] 2021-11-11 06:24
Hello,

The new version 1.68.10 work perfectly in regards to the external diff (with and without LFS) ! The delay is gone, as soon as I press CTRL+D the cursor changes shape and soon after it opens the external diff.

Thank you again for your great work !!!
Regards,
Octavian

**Comment by DanPristupov** [comment] 2021-11-11 06:34
> The new version 1.68.10 work perfectly in regards to the external diff (with and without LFS) ! The delay is gone, as soon as I press CTRL+D the cursor changes shape and soon after it opens the external diff.

This is great! Thank you for the feedback. We will test the external diff a little bit more and release a hotfix.

P.S. I didn't recognize you at first because of the new picture :)

**Closed as completed** 2024-02-27 15:09 UTC
