### ISSUE TITLE
Choose Local / Remote buttons' functions are swapped

### ISSUE THREAD

**Issue by shootie22** [ForkIssues/TrackerWin#239] opened 2019-04-19 13:19 UTC
On the latest version (1.31.1.0) the choose remote (theirs) and choose local (ours) buttons are swapped. If you have a conflict and you wish to keep your file and you click choose local, Fork chooses the remote file. Thankfully i didn't lose a lot of work, but it is definitely annoying.

**Comment by DanPristupov** [comment] 2019-04-19 13:36
You didn't mention the most important information: did you merge or rebase?

**Comment by shootie22** [comment] 2019-04-19 13:49
I didn't merge. I chose Resolve manually

**Comment by DanPristupov** [comment] 2019-04-19 13:56
OK, can you write steps to reproduce?
But first, ensure that you are not mistaken, because during rebase the ours/theirs order is opposite.

**Comment by shootie22** [comment] 2019-04-19 14:15
I haven't ever touched rebase in fork, that's for sure.  
Steps to reproduce would be to have a modified local file, try to pull a commit which also has that file modified, the conflict window appears, the yellow bar up top appears saying Fix Manually / Merge (something like that), you click Fix Manually, untick Choose Theirs (so Choose local (ours) stays checked), click choose and that's it.

**Comment by DanPristupov** [comment] 2019-04-19 14:54
OK, I'll try.
In any case I'd recommend to not rely on the ours/theirs words since they can be confusing quite often.

**Comment by shootie22** [comment] 2019-04-19 15:00
We always try that, but this time the guy who submitted the commit wasn't paying attention to see that he didn't modify that file (in UE4 even if you don't change a level map, for example, it sometimes wants to save itself and appears in git as if you modified it) so he pushed it and i, who actually modified it, pulled the commit and that happened.

**Comment by DanPristupov** [comment] 2019-04-19 15:05
I can't reproduce that.
I made pull which caused conflict, selected `local` (i.e. unchecked `theirs`) and the conflict was resolved with `local` version (mine) (i.e. the file disappeared from the changed file list).


Details:

Local commit (master):
<img width="911" alt="image" src="https://user-images.githubusercontent.com/618115/56430086-7f941000-62c5-11e9-94d9-0b0175686462.png">

Remote commit (origin/master):
<img width="911" alt="image" src="https://user-images.githubusercontent.com/618115/56430096-8b7fd200-62c5-11e9-8885-9891374bf3d9.png">

Merge conflict:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/618115/56430215-f4674a00-62c5-11e9-87bf-38776d0437df.png">

Proof:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/618115/56430139-b407cc00-62c5-11e9-8a8b-59cf2badbe71.png">

Select local:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/618115/56430155-c1bd5180-62c5-11e9-8132-e36cc8d33f8d.png">

Result (empty list, because local is identical to the working directory):
<img width="250" alt="image" src="https://user-images.githubusercontent.com/618115/56430192-ddc0f300-62c5-11e9-9914-ddaa0a01a2e4.png">

**Comment by shootie22** [comment] 2019-04-19 15:24
I don't understand how that works. You choose to keep yours and then it deletes it. How is this supposed to be the right way? Where does your local file go?

**Comment by DanPristupov** [comment] 2019-04-19 16:08
> You choose to keep yours and then it deletes it.

I chose to keep mine and it means that I already have them. That's why they are **mine**. So, we don't need to apply those changes, we already have them.

**Comment by shootie22** [comment] 2019-04-19 18:04
No we don't have them if it deletes it. After I clicked "choose ours", I opened UE4 to see whether the change was still there or if it removed it and sure enough, it got removed and i needed to do what i did again.

**Comment by shootie22** [comment] 2019-04-22 19:54
Another team member had to deal with the exact same situation today and the result was the same. He chose "Choose Ours (local)" and then it deleted his modified file. I showed him your response too and he didn't think it is right either.  
Fork deleted your modified file when you tell it to keep it. I don't see how this is how it's supposed to be.

**Comment by DanPristupov** [comment] 2019-04-22 20:24
I need either a sample repo or clear steps to reproduce the problem. Right now I still don't understand the problem.

**Comment by jerone** [comment] 2019-04-22 21:11
I just wanted to add that we have encountered the same issue at our work. As far as I know it happened two times, but we thought it might be us. 
The next time it happens again, we will report back with clear steps.

**Comment by DanPristupov** [comment] 2019-04-22 21:19
What operation caused that? Was it merge, pull or rebase?
Does content type (binary/text) matter?

**Comment by jerone** [comment] 2019-04-22 21:27
Last time happened a few weeks ago, so I don't remember the specific details. I do remember it was merge with text files.
As soon as it happens again, I'll report back.

**Comment by shootie22** [comment] 2019-04-22 21:34
I'm able to replicate it every time.  
It seems the same behavior is present with all files, not only with binary files:  
  
I created a repository, cloned it to local. Edited it from the web interface and pushed it through the web too. I then modified the same file (readme.md) locally and then tried to pull. A conflict appeared and i clicked on resolve. Unticked "Theirs (Remote)" and clicked "Choose local (ours).   
![Fork_2019-04-23_00-24-49](https://user-images.githubusercontent.com/39218788/56532762-18918800-655f-11e9-9366-760eb0397508.png)
It then deleted the file.  
![Fork_2019-04-23_00-25-30](https://user-images.githubusercontent.com/39218788/56532778-1f1fff80-655f-11e9-9da6-73bf066a0f28.png)  
The locally modified version of the file is present in the Fork Autostash that Fork creates when stashing, which is great for text files because it acts like a backup, but it's useless for binary files as you can't access them iirc.  
![mspaint_2019-04-23_00-36-32](https://user-images.githubusercontent.com/39218788/56533192-dddc1f80-655f-11e9-88b3-40f96063c740.png)

**Comment by DanPristupov** [comment] 2019-04-23 12:09
> The locally modified version of the file is present in the Fork Auto**stash** that Fork creates

So, the conflict is caused by applying a **stash**.

In this way: your repository source is local (ours) and the applied changes are remote (theirs).

Yes, this can be confusing but it's not a bug.

Any idea how we can improve that?

**Comment by shootie22** [comment] 2019-04-23 18:25
Just make the files saved in the autostash reapply (reappear) when you choose to keep yours (local). It's the most rational thing it should do when you click that button in my opinion.  
I don't see a way to download / reapply the autostashed files manually after this scenario. It's not a problem for text files, but binary files are basically lost when this happens.

**Comment by DanPristupov** [comment] 2019-04-24 06:34
> Just make the files saved in the autostash reapply (reappear) when you choose to keep yours (local). 

This won't work.

1. There's no info about how the conflict occurred. I.e. it's not possible to find out whether it was caused by a patch or stash.
2. This will lead to opposite result comparing to git (`git-checkout --ours`)

> I don't see a way to download / reapply the autostashed files manually after this scenario

Aren't the changes still in the stash?
We probably need to have a 'save as...' button in binary diff view.

**Comment by shootie22** [comment] 2019-04-24 10:08
Yeah, a save as button for binary files, (for text files too, why not), would be welcome. But what do if there are a lot of files? One ideas that comes to mind would be to give them checkboxes and an option to select / deselect them all.

**Closed as completed** 2020-04-02 12:17 UTC
