### ISSUE TITLE
Inconsistent conflicts status after custom merge tool was used

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#110] opened 2019-01-15 05:47 UTC
Merge tool (it was kdiff3) successfully resolved all conflicts, but I cannot continue cherry-pick:

![fork_2019-01-15_08-43-20](https://user-images.githubusercontent.com/7280273/51161088-1655c880-18a2-11e9-8326-a689635ef23d.png)

**Comment by jerone** [comment] 2019-01-29 13:51
I have the same. If I use an external tool (like KDiff3) to solve all conflicts, the right window says solved, but the file does not move to staged files. If I used the internal merge tool, then it does move to staged files.

In below screenshot the two left-over files were merged with KDiff3, but stayed in unstaged files list. While other files merged with the internal merge tool, where succesfully moved to staged files.

![image](https://user-images.githubusercontent.com/55841/51912604-088d6080-23d5-11e9-976f-3926f367ae3f.png)

**Comment by DanPristupov** [comment] 2019-01-29 13:58
Edited: Everything is correct. Just stage the resolved files and carry on. Fork for Windows never staged automatically conflicts resolved with 3rd party tools. The problem is that there's no quick and reliable way to determine if a conflict is resolved.

The Mac version had automatic staging in the past and sometimes people were confused by it. So, I removed it recently.

original message: I removed automatic staging for 3rd party tools some time ago. Now you need to stage files manually.

**Comment by DanPristupov** [comment] 2019-01-29 14:06
Since we are here, the next Fork update the native merge conflict resolver will get the ability to edit manually merge conflict result.

**Comment by sm-g** [comment] 2019-01-29 14:24
> Just stage the resolved files and carry on

you should add this tip somewhere in UI

**Comment by DanPristupov** [comment] 2019-01-29 14:28
@sm-g 

> ![fork_2019-01-15_08-43-20](https://user-images.githubusercontent.com/7280273/51161088-1655c880-18a2-11e9-8326-a689635ef23d.png)

"You can stage the file now" :)

**Comment by sm-g** [comment] 2019-01-29 15:05
@DanPristupov this not working for some users, as you can see

I see "fix 1 conflict" and "all conflicts resolved" and think that something not works.
Maybe use some "not completed" icon instead of this green ✔️.

Or this will not be need after the next update?

**Comment by DanPristupov** [comment] 2019-01-29 15:23
No, next update will only improve the internal merger, which is not related to that.

However, I will try to make the layout more clear.

**Comment by jerone** [comment] 2019-01-29 20:40
[**@sm-g**](https://github.com/sm-g) commented on [Jan 29, 2019, 4:05 PM GMT+1](https://github.com/ForkIssues/TrackerWin/issues/110#issuecomment-458573455 "2019-01-29T15:05:13Z - Replied by Github Reply Comments"):
> [@DanPristupov](https://github.com/DanPristupov) this not working for some users, as you can see
> 
> I see "fix 1 conflict" and "all conflicts resolved" and think that something not works.  
> 
> Maybe use some "not completed" icon instead of this green <g-emoji class="g-emoji" alias="heavy_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2714.png" title=":heavy_check_mark:">✔️</g-emoji>.

I agree that the layout is a bit confusing, with the ✔️ on the right and the ⚠ at the top. Which one is true, is my question then.

**Comment by sm-g** [comment] 2019-02-05 13:48
@DanPristupov How this should work at all? I do not understand, whats going on during conflict resolving.

My case:
1) get situation like in screenshot
2) use kdiff3 to resolve conflicts
3) stage file (still ⚠, but it worked)
4) edit commit message - remove `#`-commented lines
5) press Continue Rebase - staged files commited
6) press Resolve on top - nothing changes
7) press Continue Rebase again - got Error window and another conflicts of merge
8) resolve them

and there is still wrong commit (with `# This is a combination of 2 commits.` commit)

**Comment by DanPristupov** [comment] 2019-02-05 14:20
@sm-g Are you rebasing? During rebase commit message should not be editable 🤔.

Generally it should work like that (for rebase):
1. Start rebase.
2. If a conflict occurred, resolve all file conflicts. Stage them.
3. Press "Continue Rebase"
If another conflict occurred, repeat 2-3.

**Comment by sm-g** [comment] 2019-02-07 12:07
@DanPristupov What will happen when I press "resolve" button in this state?

![](https://i.imgur.com/XSz29zF.png)

from this state I 
1) press Continue rebase
2) looking at empty Changes screen... press Resolve. Nothing. 
3) Press Continue rebase. Nothing
4) Press Continue rebase again. Got Error and - hooray - conflicts for next commit.

**Closed as completed** 2023-10-02 12:08 UTC
