### ISSUE TITLE
Enhancement request: Show history for deleted files without locating commit that contained it

### ISSUE THREAD

**Issue by ccecvb** [ForkIssues/TrackerWin#2295] opened 2024-08-13 12:45 UTC
In the history view you can see the history of a file.

It would be nice if we could open that view directly for a deleted file without first locatiing a commit that still contained the file.

To see this for a deleted file you first need to open the console 

* git log --all -- deleted-source-path
* get the commit message of a commit that contains the file
* find that commit in fork
* find the file in that commit
* open the history view.

It would be nice if you could open the history view and just enter the filename.

This could be further enhanced by adding a view that lists all files, optionally including deleted files

**Comment by DanPristupov** [comment] 2024-08-13 14:40
This is a duplicate of https://github.com/fork-dev/TrackerWin/issues/1875

**Closed as completed** 2024-10-09 09:55 UTC
