### ISSUE TITLE
Cannot list branches from remotes with a slashed name

### ISSUE THREAD

**Issue by Erinaaaaaaa** [ForkIssues/TrackerWin#2308] opened 2024-08-27 15:06 UTC
If the remote has a slash in its name, Fork will not be able to list the branches from that remote

![image](https://github.com/user-attachments/assets/07ce851f-d1ab-463f-b9cb-70cac90108e7)

**Comment by DanPristupov** [comment] 2024-08-27 15:10
Duplicate of https://github.com/fork-dev/TrackerWin/issues/2053

**Closed as completed** 2024-10-10 09:16 UTC
