### ISSUE TITLE
Open file with no default editor

### ISSUE THREAD

**Issue by raxmet** [ForkIssues/TrackerWin#1162] opened 2021-04-30 08:52 UTC
If you add another context menu on file option like "Open with..." it will be very helpful.

**Comment by DanPristupov** [comment] 2021-05-01 14:04
This seems like a duplicate of https://github.com/fork-dev/TrackerWin/issues/109

**Comment by raxmet** [comment] 2021-05-11 14:48
yes you are absolutely right

**Closed as completed** 2021-05-11 14:49 UTC
