### ISSUE TITLE
[Feature Request] Add VSCode to 'Open In' menu

### ISSUE THREAD

**Issue by JoelCrosby** [ForkIssues/TrackerWin#307] opened 2019-06-08 21:37 UTC
This feature is present in the Mac version.

Is there any reason this isn't in the windows version?

code.exe isn't guaranteed to be on PATH but this can be verified by checking the --version output.

VS Code cli docs
[https://code.visualstudio.com/docs/editor/command-line](https://code.visualstudio.com/docs/editor/command-line)

**Comment by DanPristupov** [comment] 2019-06-08 21:50
The reason is lack of API to show available editors on Windows.

https://github.com/ForkIssues/TrackerWin/issues/109

**Comment by DanPristupov** [comment] 2019-06-10 07:26
I just realized, you probably meant the dropdown on the toolbar. This feature is in our todo list then.

**Comment by vtintillier** [comment] 2019-07-24 06:39
Hello @DanPristupov 

I have 1.37.1 installed but cannot see any entry for VSCode:

![image](https://user-images.githubusercontent.com/494652/61770849-8794ac00-adee-11e9-9188-165406db4a0a.png)

Is this a known issue? Do I need to configure something?

Thanks

**Comment by DanPristupov** [comment] 2019-07-24 06:48
Is your VSCode installed to the default location?

Fork tries to find it at the following places:
- `%localappdata%\Programs\Microsoft VS Code\Code.exe`
- `%programfiles(x86)%\Microsoft VS Code\Code.exe`

**Comment by vtintillier** [comment] 2019-07-24 07:03
It seems so (windows 10 x64): `"C:\Program Files\Microsoft VS Code\Code.exe"`

**Comment by elendil-software** [comment] 2019-07-24 07:14
> 
> 
> Is your VSCode installed to the default location?
> 
> Fork tries to find it at the following places:
> 
>     * `%localappdata%\Programs\Microsoft VS Code\Code.exe`
> 
>     * `%programfiles(x86)%\Microsoft VS Code\Code.exe`

I think the path `%programfiles%\Microsoft VS Code\Code.exe` should be added to this list

Regards,

Julien

**Comment by DanPristupov** [comment] 2019-07-24 07:19
@elendil-software yes.

In addition to this, Fork should check the `%CODE%` environment library.

ETA: 1.38.

**Comment by DanPristupov** [comment] 2019-08-16 15:13
We added `%programfiles%\Microsoft VS Code\Code.exe` in 1.38.

P.S. I was wrong about `%CODE%`, it doesn't exist.

**Comment by Stanzilla** [comment] 2019-08-16 15:16
@DanPristupov just tested 1.38 and it still does not show the menu entry. my VSCode is installed in `"C:\Program Files\Microsoft VS Code\Code.exe"`

**Comment by DanPristupov** [comment] 2019-08-16 15:21
:(

What is `%programfiles%` on your computer?
Does VS start when you run `%programfiles%\Microsoft VS Code\Code.exe` in command line?

**Comment by Stanzilla** [comment] 2019-08-16 15:38
`C:\Program Files` is correct and yea it starts if you run `"%programfiles%\Microsoft VS Code\Code.exe"` did you maybe forget to quote the path?

**Comment by vtintillier** [comment] 2019-08-19 07:29
Same here with 1.38, does not work.

**Comment by vtintillier** [comment] 2019-08-19 07:30
Same here with 1.38, does not work.

**Comment by elendil-software** [comment] 2019-08-20 13:35
Same here.

>  Does VS start when you run `%programfiles%\Microsoft VS Code\Code.exe` in command line?

Yes

**Comment by thelovebug** [comment] 2019-09-10 15:03
I've managed to get this to work in 1.38, but only if the path associated with the selected repository doesn't contain spaces, else it opens a blank file up to the first space and another blank file associated with whatever is after the first space.  I would imagine that if there were multiple spaces, there would be more blank files opened.

**For example:**
Repository: `C:\Folder1\Folder2\Folder Three\Repo.Name\` will open:

1. a blank file called **`C:\Folder1\Folder2\Folder`**
2. a blank file called `C:\Users\MyUser\AppData\Local\Fork\app-1.38.0\`**`Three\Repo.Name`**

_(ignore the space before_ **`Three`** _in point 2 above, that's just a formatting quirk where I've tried to demonstrate where the issue is)_

My guess is that where the path is being passed to VSCode, it would need to have "quotes" around it.

**Comment by Stanzilla** [comment] 2019-09-10 15:08
Hah so exactly what I suspected, classic path problems

**Comment by DanPristupov** [comment] 2019-09-10 15:13
BTW, the problem with invisible item will be fixed in 1.39 which is planned for this Friday.

The problem was that in 32bit process `%programfiles%` leads to 'Program Files (x86)'. I had to use `%ProgramW6432%` instead.

**Comment by DanPristupov** [comment] 2019-09-10 15:14
@thelovebug I'll have a look on that.

**Comment by DanPristupov** [comment] 2019-09-13 15:31
Please check if we've fixed the problem once you update to 1.39.

@thelovebug the problem with space in repository path should also be fixed.

**Comment by Stanzilla** [comment] 2019-09-13 15:53
Can confirm it works now, thanks!

**Comment by vtintillier** [comment] 2019-09-14 10:21
+1, works fine, thanks

**Closed as completed** 2019-09-22 11:29 UTC
