### ISSUE TITLE
Error when trying to fetch

### ISSUE THREAD

**Issue by shootie22** [ForkIssues/TrackerWin#49] opened 2018-11-21 09:43 UTC
OS: Windows 10
Version: 1.23.5.0

When i am trying to fetch it gives out an error:
```
fatal: NullReferenceException encountered.
   Object reference not set to an instance of an object.

```

I am able to fetch manually with `git fetch` via the terminal and with other git clients.

**Comment by DanPristupov** [comment] 2018-11-21 11:01
This could be a bug in git 2.19.1: https://stackoverflow.com/a/53150841/6116850

Could you show output of the `git version` from the terminal where fetch works?
Do you have BitBucket + HTTPS?
Does fetch work in terminal when you open it using the button on the toolbar in Fork?

**Comment by shootie22** [comment] 2018-11-21 11:46
git version 2.17.1.windows.2 in the terminal i open from the terminal button in fork. and yes, fetch works from there but it asks for my username and password every time. 
we use Gitea and have LFS enabled. and yes, we are using it through HTTPS.

**Comment by Schreini** [comment] 2018-11-22 15:51
A new Version of Git for Windows has been released with GCM 1.18.3 wich fixes this Issue.

https://github.com/git-for-windows/git/releases/tag/v2.19.2.windows.1

**Comment by DanPristupov** [comment] 2018-11-24 12:49
I'm still struggling to find a proof that the problem is fixed.

The release notes doesn't give much info.

https://github.com/git-for-windows/git/releases/tag/v2.19.2.windows.1 doesn't mention anything.

https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/1.18.3 has the following:

> Environment Variables containing duplicate, different case, keys shouldn't cause GCM to fail

It that the one we want to be fixed?

**Comment by DanPristupov** [comment] 2018-11-24 12:52
I can't reproduce that bug at all.

In different thread (https://github.com/ForkIssues/TrackerWin/issues/50) @beppler said that 1.18.3 does fix the bug.

However @warnat in (https://github.com/ForkIssues/TrackerWin/issues/51) said exactly the opposite:
> GCM 1.18.3 did not help

It could be great if @jeschu1 who released GCM 1.18.3, could confirm that (or not).

**Comment by beppler** [comment] 2018-11-24 19:54
You should update the git that comes with git-fork, not the main git install on your machine.
It worked when I unzipped the GCM ZIP on folder `gitInstance\2.19.1\mingw64\libexec\git-core` inside the git-fork install folder.

**Comment by warnat** [comment] 2018-11-25 17:29
@DanPristupov : I solved #51 now.

**Comment by DanPristupov** [comment] 2018-11-26 10:54
Just released Fork 1.24 with git 1.19.2 and some other features.

Please check for updates and let me know if the problem is fixed.

**Comment by shootie22** [comment] 2018-11-26 19:46
Yes, the issue seems to have been fixed with the latest update. Fetch is working as usual now. Thanks a lot!

**Comment by DanPristupov** [comment] 2018-11-26 19:56
@urgaylol great! Thank you for getting back

**Closed as completed** 2018-11-26 19:56 UTC
